/**
 * @name get parallel pages simons 
 * @name puppeteer
 * @name csv-writer
 * @desc Allow parallel processing content
 */

const puppeteer = require('puppeteer')
const writeFile = require('fs');
const JSONToCSV = require("json2csv").parse;
// const  createCsvWriter = require('csv-writer').createObjectCsvWriter;
const parallel = 2; //separate interrior run

(async () => {

    //list prods copy from excel file
    const list = [
        "https://weedmaps.com/doctors/pharmacann-clinic-2",
"https://weedmaps.com/deliveries/exclusive-bud",
"https://weedmaps.com/dispensaries/sqdc-montreal3",
"https://weedmaps.com/deliveries/kali-ma-exotics",
"https://weedmaps.com/deliveries/metro-buds-mtl-1",
"https://weedmaps.com/deliveries/marche420",
"https://weedmaps.com/deliveries/cream-of-the-crop-22c07d45-396b-4af5-8ed4-6b79341e7d9c",
"https://weedmaps.com/dispensaries/sqdc-rosemont",
"https://weedmaps.com/doctors/sante-cannabis",
"https://weedmaps.com/doctors/alpha-cure-consulting-4",
"https://weedmaps.com/dispensaries/sqdc-mascouche",
"https://weedmaps.com/doctors/namaste-md-3",
"https://weedmaps.com/dispensaries/sqdc-montreal2",
"https://weedmaps.com/deliveries/thc-collection-2",
"https://weedmaps.com/deliveries/budbargain-ca-3",
"https://weedmaps.com/deliveries/gas-city-06709553-6bfd-4d00-93b3-b3746e256318",
"https://weedmaps.com/doctors/thcity-inc-2",
"https://weedmaps.com/doctors/curativecare-ca",
"https://weedmaps.com/deliveries/buymyweedonline-ca-4",
"https://weedmaps.com/doctors/thcentral-inc",
"https://weedmaps.com/doctors/cannabis-advocates",
"https://weedmaps.com/doctors/my-grow-4",
"https://weedmaps.com/dispensaries/sqdc-drummondville-store",
"https://weedmaps.com/deliveries/west-coast-cannabis-4",
"https://weedmaps.com/deliveries/bud-n-beyond-2",
"https://weedmaps.com/dispensaries/sqdc-joliette",
"https://weedmaps.com/doctors/thcity-inc-3",
"https://weedmaps.com/doctors/centre-medical-cannabis-consultants",
"https://weedmaps.com/dispensaries/clinique-la-croix-verte-2-2",
"https://weedmaps.com/dispensaries/sqdc-st-jean-sur-richelieu",
"https://weedmaps.com/deliveries/smartbudz-5",
"https://weedmaps.com/doctors/thcity-inc",
"https://weedmaps.com/doctors/medical-cannabis-group-7",
"https://weedmaps.com/deliveries/deli-geez",
"https://weedmaps.com/dispensaries/satnaam-edibles",
"https://weedmaps.com/deliveries/mota-cannabis-products-6",
"https://weedmaps.com/deliveries/healingempire-ca-4",
"https://weedmaps.com/doctors/dr-cannabis-36479ebe-3d39-4b3d-a30f-a2a92fe89101",
"https://weedmaps.com/doctors/dr-cannabis-10",
"https://weedmaps.com/doctors/cool-kind-4",
"https://weedmaps.com/doctors/licence-to-grow",
"https://weedmaps.com/doctors/medscriptter-3",
"https://weedmaps.com/deliveries/northern-flowers",
"https://weedmaps.com/deliveries/quebec-gold",
"https://weedmaps.com/dispensaries/sqdc-mirabel",
"https://weedmaps.com/doctors/medical-marijuana-services-3",
"https://weedmaps.com/dispensaries/sqdc-trois-rivieres",
"https://weedmaps.com/deliveries/marche420-2",
"https://weedmaps.com/doctors/pharmacann-clinic",
"https://weedmaps.com/deliveries/georgia-peach-online-3",
"https://weedmaps.com/deliveries/big-nugs-3",
"https://weedmaps.com/deliveries/marche420-1",
"https://weedmaps.com/deliveries/bud-n-beyond-1",
"https://weedmaps.com/dispensaries/sqdc-brossard-coming-soon",
"https://weedmaps.com/doctors/thculture",
"https://weedmaps.com/deliveries/bud-bros-1",
"https://weedmaps.com/doctors/shevaya-wellness",
"https://weedmaps.com/deliveries/cannamedics-ca-7",
"https://weedmaps.com/dispensaries/le-710-stjerome-inc",
"https://weedmaps.com/dispensaries/sqdc-montreal1",
"https://weedmaps.com/doctors/thc-the-human-corporation",
"https://weedmaps.com/deliveries/dank-delivery-online-7",
"https://weedmaps.com/doctors/thcity-plateau-mont-royal-inc",
"https://weedmaps.com/deliveries/beleave-4",
"https://weedmaps.com/doctors/the-leefs-company-2",
"https://weedmaps.com/doctors/accmq",
"https://weedmaps.com/deliveries/bc-royal-1",
"https://weedmaps.com/deliveries/capital-kush-2",
"https://weedmaps.com/deliveries/stream-dream-cannabis",
"https://weedmaps.com/deliveries/denverdabs613-1",
"https://weedmaps.com/deliveries/budbuddies",
"https://weedmaps.com/deliveries/cannabis-depot-2",
"https://weedmaps.com/deliveries/urban-farmer",
"https://weedmaps.com/deliveries/half-baked-1",
"https://weedmaps.com/doctors/the-leefs-company-3",
"https://weedmaps.com/dispensaries/smoke-signals-pikwakanagan",
"https://weedmaps.com/deliveries/613-delivery-2",
"https://weedmaps.com/deliveries/5-star-kush-delivery",
"https://weedmaps.com/deliveries/topshelf-48",
"https://weedmaps.com/deliveries/dank-us-later",
"https://weedmaps.com/deliveries/capital-cannabis-delivery",
"https://weedmaps.com/deliveries/the-kush-firm",
"https://weedmaps.com/doctors/national-access-cannabis",
"https://weedmaps.com/deliveries/gas-station-ottawa",
"https://weedmaps.com/deliveries/sweetleaf-depot",
"https://weedmaps.com/deliveries/wild-card-delivery",
"https://weedmaps.com/deliveries/the-highlife",
"https://weedmaps.com/doctors/canadian-cannabis-clinic",
"https://weedmaps.com/deliveries/cannagethigh",
"https://weedmaps.com/doctors/canada-house-clinics-9",
"https://weedmaps.com/deliveries/true-north-relief",
"https://weedmaps.com/deliveries/kusharama-8",
"https://weedmaps.com/dispensaries/superette",
"https://weedmaps.com/deliveries/downtoearth",
"https://weedmaps.com/deliveries/cannabis-co-canada",
"https://weedmaps.com/deliveries/ottawa-bud",
"https://weedmaps.com/deliveries/my-ottawa-delivery",
"https://weedmaps.com/deliveries/culture-cannabis",
"https://weedmaps.com/deliveries/wee-d-liver",
"https://weedmaps.com/deliveries/ounce-house-1",
"https://weedmaps.com/deliveries/city-cannabis-co",
"https://weedmaps.com/doctors/hybrid-pharm",
"https://weedmaps.com/deliveries/lifted-deliveries",
"https://weedmaps.com/doctors/dr-cannabis-consult-4",
"https://weedmaps.com/doctors/bodystream-medical-marijuana",
"https://weedmaps.com/deliveries/dankdepo",
"https://weedmaps.com/deliveries/thc-collection-6",
"https://weedmaps.com/deliveries/releaf-delivery-15",
"https://weedmaps.com/deliveries/skipthebud",
"https://weedmaps.com/doctors/alpha-cure-consulting",
"https://weedmaps.com/deliveries/ottawa-kind",
"https://weedmaps.com/deliveries/curaleaf-potsdam",
"https://weedmaps.com/doctors/bodystream-cornwall",
"https://weedmaps.com/deliveries/supherbs-3",
"https://weedmaps.com/deliveries/5-star-kush-delivery-6",
"https://weedmaps.com/dispensaries/fire-flower-york-street-cannabis",
"https://weedmaps.com/deliveries/mrgreenleaf",
"https://weedmaps.com/deliveries/bc-royal",
"https://weedmaps.com/deliveries/weedmart-83e012dd-efb3-49f3-b25f-1b59e3925707",
"https://weedmaps.com/deliveries/hot-grass-11",
"https://weedmaps.com/doctors/infocannabis",
"https://weedmaps.com/deliveries/kusharama-7",
"https://weedmaps.com/dispensaries/hobo-cannabis-company-opening-soon",
"https://weedmaps.com/deliveries/cannabis-depot-1",
"https://weedmaps.com/deliveries/fastngassy",
"https://weedmaps.com/deliveries/culture-cannabis-kingston",
"https://weedmaps.com/doctors/namaste-md-4",
"https://weedmaps.com/doctors/dr-cannabis-9",
"https://weedmaps.com/deliveries/weed-on-the-go-1",
"https://weedmaps.com/deliveries/true-north-relief-2",
"https://weedmaps.com/deliveries/cannabis-express-1",
"https://weedmaps.com/doctors/cannabinoid-medical-clinic-3",
"https://weedmaps.com/deliveries/the-barn-mobile",
"https://weedmaps.com/deliveries/bc-thc-613",
"https://weedmaps.com/doctors/medical-marijuana-services-5",
"https://weedmaps.com/doctors/holistic-on-call-11",
"https://weedmaps.com/deliveries/marche420-1",
"https://weedmaps.com/deliveries/kali-ma-exotics",
"https://weedmaps.com/dispensaries/bud-shack",
"https://weedmaps.com/dispensaries/satnaam-edibles",
"https://weedmaps.com/doctors/pharmacann-clinic-2",
"https://weedmaps.com/doctors/thcentral-inc",
"https://weedmaps.com/deliveries/budbargain-ca-3",
"https://weedmaps.com/deliveries/thc-collection-2",
"https://weedmaps.com/deliveries/sqdc",
"https://weedmaps.com/doctors/serenity-medical-online-2",
"https://weedmaps.com/dispensaries/clinique-la-croix-verte-2-2",
"https://weedmaps.com/doctors/accmq",
"https://weedmaps.com/deliveries/healingempire-ca-4",
"https://weedmaps.com/deliveries/big-nugs-3",
"https://weedmaps.com/doctors/namaste-md-3",
"https://weedmaps.com/doctors/cannabis-advocates",
"https://weedmaps.com/deliveries/gas-city-06709553-6bfd-4d00-93b3-b3746e256318",
"https://weedmaps.com/doctors/pharmacann-clinic-kanesatake",
"https://weedmaps.com/deliveries/exclusive-bud",
"https://weedmaps.com/deliveries/cream-of-the-crop-22c07d45-396b-4af5-8ed4-6b79341e7d9c",
"https://weedmaps.com/dispensaries/smoke-signals-kanehsatake-3",
"https://weedmaps.com/doctors/alpha-cure-consulting-4",
"https://weedmaps.com/doctors/the-leefs-company-2",
"https://weedmaps.com/dispensaries/sqdc-montreal2",
"https://weedmaps.com/deliveries/curaleaf-malone",
"https://weedmaps.com/doctors/thcity-inc",
"https://weedmaps.com/doctors/cool-kind-4",
"https://weedmaps.com/deliveries/northern-flowers",
"https://weedmaps.com/doctors/pharmacann-clinic",
"https://weedmaps.com/doctors/shevaya-wellness",
"https://weedmaps.com/doctors/bodystream-cornwall",
"https://weedmaps.com/deliveries/georgia-peach-online-3",
"https://weedmaps.com/dispensaries/the-medicine-box",
"https://weedmaps.com/deliveries/curaleaf-plattsburgh",
"https://weedmaps.com/doctors/thculture",
"https://weedmaps.com/doctors/sante-cannabis",
"https://weedmaps.com/deliveries/marche420",
"https://weedmaps.com/deliveries/mota-cannabis-products-6",
"https://weedmaps.com/deliveries/bud-n-beyond-1",
"https://weedmaps.com/dispensaries/sqdc-mirabel",
"https://weedmaps.com/doctors/thcity-vaudreuil",
"https://weedmaps.com/doctors/medical-cannabis-group-7",
"https://weedmaps.com/dispensaries/le-710-stjerome-inc",
"https://weedmaps.com/doctors/heally-online-7",
"https://weedmaps.com/dispensaries/sqdc-montreal1",
"https://weedmaps.com/doctors/thcity-plateau-mont-royal-inc",
"https://weedmaps.com/doctors/prestodoctor-10",
"https://weedmaps.com/doctors/le-57",
"https://weedmaps.com/deliveries/buymyweedonline-ca-4",
"https://weedmaps.com/doctors/licence-to-grow",
"https://weedmaps.com/dispensaries/mary-jane-s-medical-marijuana",
"https://weedmaps.com/doctors/my-grow-4",
"https://weedmaps.com/deliveries/beleave-4",
"https://weedmaps.com/doctors/medscriptter-3",
"https://weedmaps.com/doctors/centre-medical-cannabis-consultants",
"https://weedmaps.com/deliveries/marche420-2",
"https://weedmaps.com/deliveries/bud-bros-1",
"https://weedmaps.com/dispensaries/sqdc-drummondville-store",
"https://weedmaps.com/deliveries/cannamedics-ca-7",
"https://weedmaps.com/dispensaries/cannacentral",
"https://weedmaps.com/doctors/upstate-medicinal-alternatives",
"https://weedmaps.com/doctors/thcity-inc-3",
"https://weedmaps.com/deliveries/west-coast-cannabis-4",
"https://weedmaps.com/deliveries/deli-geez",
"https://weedmaps.com/doctors/thc-the-human-corporation",
"https://weedmaps.com/deliveries/dank-delivery-online-7",
"https://weedmaps.com/deliveries/metro-buds-mtl-1",
"https://weedmaps.com/doctors/medical-marijuana-services-3",
"https://weedmaps.com/doctors/dr-cannabis-36479ebe-3d39-4b3d-a30f-a2a92fe89101",
"https://weedmaps.com/doctors/curativecare-ca",
"https://weedmaps.com/dispensaries/sqdc-mascouche",
"https://weedmaps.com/dispensaries/sqdc-brossard-coming-soon",
"https://weedmaps.com/dispensaries/curaleaf-ny-plattsburgh",
"https://weedmaps.com/dispensaries/sqdc-montreal3",
"https://weedmaps.com/dispensaries/sqdc-joliette",
"https://weedmaps.com/dispensaries/the-dispensary-9",
"https://weedmaps.com/doctors/dr-cannabis-10",
"https://weedmaps.com/deliveries/quebec-gold",
"https://weedmaps.com/deliveries/smartbudz-5",
"https://weedmaps.com/deliveries/bud-n-beyond-2",
"https://weedmaps.com/dispensaries/sqdc-st-jean-sur-richelieu",
"https://weedmaps.com/deliveries/bc-royal-1",
"https://weedmaps.com/dispensaries/sqdc-rosemont",
"https://weedmaps.com/deliveries/bud-n-beyond-1",
"https://weedmaps.com/doctors/new-england-medicine-counseling-associates",
"https://weedmaps.com/dispensaries/mary-jane-s-medical-marijuana",
"https://weedmaps.com/doctors/cool-kind-4",
"https://weedmaps.com/deliveries/metro-buds-mtl-1",
"https://weedmaps.com/doctors/curativecare-ca",
"https://weedmaps.com/doctors/shevaya-wellness",
"https://weedmaps.com/deliveries/buymyweedonline-ca-4",
"https://weedmaps.com/doctors/heally-online-7",
"https://weedmaps.com/deliveries/budbargain-ca-3",
"https://weedmaps.com/dispensaries/sqdc-montreal3",
"https://weedmaps.com/deliveries/curaleaf-plattsburgh",
"https://weedmaps.com/doctors/pharmacann-clinic",
"https://weedmaps.com/dispensaries/smoke-signals-kanehsatake-3",
"https://weedmaps.com/dispensaries/sqdc-drummondville-store",
"https://weedmaps.com/doctors/licence-to-grow",
"https://weedmaps.com/dispensaries/sqdc-montreal2",
"https://weedmaps.com/dispensaries/clinique-la-croix-verte-2-2",
"https://weedmaps.com/deliveries/curaleaf-malone",
"https://weedmaps.com/deliveries/dank-delivery-online-7",
"https://weedmaps.com/doctors/namaste-md-3",
"https://weedmaps.com/dispensaries/sqdc-rosemont",
"https://weedmaps.com/deliveries/quebec-gold",
"https://weedmaps.com/doctors/thc-the-human-corporation",
"https://weedmaps.com/dispensaries/sqdc-mascouche",
"https://weedmaps.com/dispensaries/cannacentral",
"https://weedmaps.com/doctors/sante-cannabis",
"https://weedmaps.com/dispensaries/curaleaf-ny-plattsburgh",
"https://weedmaps.com/doctors/thcity-inc-3",
"https://weedmaps.com/deliveries/cannamedics-ca-7",
"https://weedmaps.com/deliveries/sqdc",
"https://weedmaps.com/doctors/thcentral-inc",
"https://weedmaps.com/doctors/thculture",
"https://weedmaps.com/dispensaries/sqdc-joliette",
"https://weedmaps.com/doctors/holistic-on-call-11",
"https://weedmaps.com/doctors/dr-cannabis-36479ebe-3d39-4b3d-a30f-a2a92fe89101",
"https://weedmaps.com/doctors/medical-cannabis-group-7",
"https://weedmaps.com/doctors/centre-medical-cannabis-consultants",
"https://weedmaps.com/doctors/accmq",
"https://weedmaps.com/doctors/pharmacann-clinic-2",
"https://weedmaps.com/deliveries/bc-royal-1",
"https://weedmaps.com/dispensaries/the-medicine-box",
"https://weedmaps.com/deliveries/exclusive-bud",
"https://weedmaps.com/deliveries/kali-ma-exotics",
"https://weedmaps.com/doctors/upstate-medicinal-alternatives",
"https://weedmaps.com/deliveries/gas-city-06709553-6bfd-4d00-93b3-b3746e256318",
"https://weedmaps.com/doctors/thcity-vaudreuil",
"https://weedmaps.com/dispensaries/le-710-stjerome-inc",
"https://weedmaps.com/deliveries/west-coast-cannabis-4",
"https://weedmaps.com/doctors/thcity-plateau-mont-royal-inc",
"https://weedmaps.com/doctors/cannabis-advocates",
"https://weedmaps.com/doctors/alpha-cure-consulting-4",
"https://weedmaps.com/deliveries/northern-flowers",
"https://weedmaps.com/deliveries/marche420",
"https://weedmaps.com/doctors/the-leefs-company-2",
"https://weedmaps.com/dispensaries/sqdc-mirabel",
"https://weedmaps.com/deliveries/mota-cannabis-products-6",
"https://weedmaps.com/doctors/le-57",
"https://weedmaps.com/deliveries/healingempire-ca-4",
"https://weedmaps.com/deliveries/thc-collection-2",
"https://weedmaps.com/doctors/bodystream-cornwall",
"https://weedmaps.com/doctors/pharmacann-clinic-kanesatake",
"https://weedmaps.com/deliveries/marche420-2",
"https://weedmaps.com/deliveries/georgia-peach-online-3",
"https://weedmaps.com/dispensaries/sqdc-st-jean-sur-richelieu",
"https://weedmaps.com/deliveries/bud-n-beyond-2",
"https://weedmaps.com/deliveries/cream-of-the-crop-22c07d45-396b-4af5-8ed4-6b79341e7d9c",
"https://weedmaps.com/deliveries/deli-geez",
"https://weedmaps.com/dispensaries/sqdc-montreal1",
"https://weedmaps.com/dispensaries/bud-shack",
"https://weedmaps.com/deliveries/marche420-1",
"https://weedmaps.com/deliveries/beleave-4",
"https://weedmaps.com/doctors/dr-cannabis-10",
"https://weedmaps.com/deliveries/big-nugs-3",
"https://weedmaps.com/doctors/thcity-inc",
"https://weedmaps.com/deliveries/smartbudz-5",
"https://weedmaps.com/doctors/medscriptter-3",
"https://weedmaps.com/dispensaries/the-dispensary-9",
"https://weedmaps.com/doctors/serenity-medical-online-2",
"https://weedmaps.com/doctors/medical-marijuana-services-3",
"https://weedmaps.com/doctors/my-grow-4",
"https://weedmaps.com/dispensaries/sqdc-brossard-coming-soon",
"https://weedmaps.com/doctors/prestodoctor-10",
"https://weedmaps.com/dispensaries/satnaam-edibles",
"https://weedmaps.com/deliveries/bud-bros-1",
"https://weedmaps.com/deliveries/smartbudz-7",
"https://weedmaps.com/doctors/dr-cannabis-11",
"https://weedmaps.com/dispensaries/sqdc",
"https://weedmaps.com/dispensaries/sqdc-levis-store",
"https://weedmaps.com/doctors/dr-cannabis-consult-8",
"https://weedmaps.com/deliveries/beleave-5",
"https://weedmaps.com/doctors/clinique-tetra",
"https://weedmaps.com/deliveries/mota-cannabis-products-8",
"https://weedmaps.com/doctors/cicm-consultant-en-cannabis-medical",
"https://weedmaps.com/doctors/centre-medical-cannabis-consultants-2",
"https://weedmaps.com/deliveries/cannamedics-ca-8",
"https://weedmaps.com/doctors/thcity-inc-2",
"https://weedmaps.com/doctors/licence-to-grow-2",
"https://weedmaps.com/dispensaries/sqdc-2",
"https://weedmaps.com/deliveries/thc-collection-7",
"https://weedmaps.com/dispensaries/sqdc-trois-rivieres",
"https://weedmaps.com/deliveries/hot-grass-12",
"https://weedmaps.com/deliveries/cannamedics-ca-7",
"https://weedmaps.com/dispensaries/sqdc-brossard-coming-soon",
"https://weedmaps.com/doctors/thcentral-inc",
"https://weedmaps.com/deliveries/metro-buds-mtl-1",
"https://weedmaps.com/doctors/cannabis-advocates",
"https://weedmaps.com/dispensaries/sqdc-mirabel",
"https://weedmaps.com/doctors/dr-cannabis-36479ebe-3d39-4b3d-a30f-a2a92fe89101",
"https://weedmaps.com/deliveries/buymyweedonline-ca-4",
"https://weedmaps.com/deliveries/marche420",
"https://weedmaps.com/dispensaries/sqdc-rosemont",
"https://weedmaps.com/doctors/medical-cannabis-group-7",
"https://weedmaps.com/doctors/thcity-vaudreuil",
"https://weedmaps.com/doctors/centre-medical-cannabis-consultants",
"https://weedmaps.com/doctors/pharmacann-clinic-2",
"https://weedmaps.com/doctors/shevaya-wellness",
"https://weedmaps.com/doctors/thcity-plateau-mont-royal-inc",
"https://weedmaps.com/dispensaries/sqdc-montreal1",
"https://weedmaps.com/deliveries/bud-n-beyond-2",
"https://weedmaps.com/dispensaries/sqdc-st-jean-sur-richelieu",
"https://weedmaps.com/doctors/thcity-inc-3",
"https://weedmaps.com/doctors/namaste-md-3",
"https://weedmaps.com/dispensaries/le-710-stjerome-inc",
"https://weedmaps.com/doctors/new-england-medicine-counseling-associates",
"https://weedmaps.com/dispensaries/mary-jane-s-medical-marijuana",
"https://weedmaps.com/deliveries/bud-n-beyond-1",
"https://weedmaps.com/deliveries/healingempire-ca-4",
"https://weedmaps.com/dispensaries/clinique-la-croix-verte-2-2",
"https://weedmaps.com/doctors/thc-the-human-corporation",
"https://weedmaps.com/deliveries/gas-city-06709553-6bfd-4d00-93b3-b3746e256318",
"https://weedmaps.com/deliveries/beleave-4",
"https://weedmaps.com/doctors/dr-cannabis-10",
"https://weedmaps.com/deliveries/sqdc",
"https://weedmaps.com/deliveries/budbargain-ca-3",
"https://weedmaps.com/doctors/medscriptter-3",
"https://weedmaps.com/doctors/pharmacann-clinic",
"https://weedmaps.com/doctors/bodystream-cornwall",
"https://weedmaps.com/dispensaries/sqdc-montreal3",
"https://weedmaps.com/dispensaries/smoke-signals-kanehsatake-3",
"https://weedmaps.com/doctors/le-57",
"https://weedmaps.com/dispensaries/sqdc-joliette",
"https://weedmaps.com/deliveries/curaleaf-malone",
"https://weedmaps.com/dispensaries/bud-shack",
"https://weedmaps.com/deliveries/mota-cannabis-products-6",
"https://weedmaps.com/deliveries/northern-flowers",
"https://weedmaps.com/doctors/holistic-on-call-11",
"https://weedmaps.com/deliveries/cream-of-the-crop-22c07d45-396b-4af5-8ed4-6b79341e7d9c",
"https://weedmaps.com/dispensaries/champlain-valley-dispensary-2",
"https://weedmaps.com/doctors/alpha-cure-consulting-4",
"https://weedmaps.com/deliveries/curaleaf-plattsburgh",
"https://weedmaps.com/doctors/serenity-medical-online-2",
"https://weedmaps.com/deliveries/kali-ma-exotics",
"https://weedmaps.com/deliveries/bc-royal-1",
"https://weedmaps.com/deliveries/exclusive-bud",
"https://weedmaps.com/deliveries/bud-bros-1",
"https://weedmaps.com/deliveries/big-nugs-3",
"https://weedmaps.com/deliveries/marche420-2",
"https://weedmaps.com/doctors/licence-to-grow",
"https://weedmaps.com/dispensaries/sqdc-drummondville-store",
"https://weedmaps.com/dispensaries/curaleaf-ny-plattsburgh",
"https://weedmaps.com/doctors/accmq",
"https://weedmaps.com/doctors/cool-kind-4",
"https://weedmaps.com/dispensaries/sqdc-montreal2",
"https://weedmaps.com/dispensaries/the-medicine-box",
"https://weedmaps.com/doctors/medical-marijuana-services-3",
"https://weedmaps.com/deliveries/quebec-gold",
"https://weedmaps.com/doctors/sante-cannabis",
"https://weedmaps.com/deliveries/deli-geez",
"https://weedmaps.com/doctors/prestodoctor-10",
"https://weedmaps.com/doctors/thcity-inc",
"https://weedmaps.com/deliveries/marche420-1",
"https://weedmaps.com/doctors/my-grow-4",
"https://weedmaps.com/deliveries/thc-collection-2",
"https://weedmaps.com/doctors/heally-online-7",
"https://weedmaps.com/doctors/curativecare-ca",
"https://weedmaps.com/dispensaries/the-dispensary-9",
"https://weedmaps.com/doctors/upstate-medicinal-alternatives",
"https://weedmaps.com/dispensaries/sqdc-mascouche",
"https://weedmaps.com/deliveries/west-coast-cannabis-4",
"https://weedmaps.com/deliveries/dank-delivery-online-7",
"https://weedmaps.com/dispensaries/satnaam-edibles",
"https://weedmaps.com/deliveries/georgia-peach-online-3",
"https://weedmaps.com/doctors/pharmacann-clinic-kanesatake",
"https://weedmaps.com/dispensaries/cannacentral",
"https://weedmaps.com/doctors/the-leefs-company-2",
"https://weedmaps.com/deliveries/smartbudz-5",
"https://weedmaps.com/doctors/thculture",
"https://weedmaps.com/dispensaries/sqdc",
"https://weedmaps.com/deliveries/beleave-5",
"https://weedmaps.com/deliveries/hot-grass-12",
"https://weedmaps.com/doctors/centre-medical-cannabis-consultants-2",
"https://weedmaps.com/dispensaries/sqdc-mascouche",
"https://weedmaps.com/dispensaries/sqdc-drummondville-store",
"https://weedmaps.com/doctors/dr-cannabis-11",
"https://weedmaps.com/deliveries/cannamedics-ca-8",
"https://weedmaps.com/doctors/clinique-tetra",
"https://weedmaps.com/doctors/dr-cannabis-consult-8",
"https://weedmaps.com/deliveries/thc-collection-7",
"https://weedmaps.com/dispensaries/sqdc-levis-store",
"https://weedmaps.com/doctors/licence-to-grow-2",
"https://weedmaps.com/dispensaries/sqdc-2",
"https://weedmaps.com/doctors/thcity-inc-2",
"https://weedmaps.com/dispensaries/sqdc-trois-rivieres",
"https://weedmaps.com/deliveries/mota-cannabis-products-8",
"https://weedmaps.com/doctors/cicm-consultant-en-cannabis-medical",
"https://weedmaps.com/deliveries/smartbudz-7",
"https://weedmaps.com/dispensaries/sqdc-joliette",
"https://weedmaps.com/deliveries/mota-cannabis-products-6",
"https://weedmaps.com/doctors/o-cannabis-clinic-7",
"https://weedmaps.com/dispensaries/nslc-truro",
"https://weedmaps.com/dispensaries/nslc-new-glasgow",
"https://weedmaps.com/deliveries/canada-s-island-garden-2",
"https://weedmaps.com/dispensaries/nslc-cannabis-amherst",
"https://weedmaps.com/doctors/go-greens-consulting-6",
"https://weedmaps.com/doctors/medical-cannabis-group-9",
"https://weedmaps.com/doctors/curativecare-ca-8",
"https://weedmaps.com/doctors/canada-house-clinics-4",
"https://weedmaps.com/doctors/cool-kind-7",
"https://weedmaps.com/dispensaries/5buds-cannabis",
"https://weedmaps.com/dispensaries/5buds-cannabis-2",
"https://weedmaps.com/dispensaries/5-buds-cannabis",
"https://weedmaps.com/dispensaries/prairie-records",
"https://weedmaps.com/dispensaries/5-buds-cannabis-2",
"https://weedmaps.com/dispensaries/fire-flower-north-battleford",
"https://weedmaps.com/dispensaries/harvest-hoc-williston",
"https://weedmaps.com/doctors/destiny-med-spa-pllc",
"https://weedmaps.com/dispensaries/around-the-clock-cannabis-plentywood",
"https://weedmaps.com/deliveries/bamboo-forest-3",
"https://weedmaps.com/deliveries/coast-to-coast-medicinals-regina",
"https://weedmaps.com/doctors/cool-kind-8",
"https://weedmaps.com/deliveries/bud-365-3",
"https://weedmaps.com/doctors/medical-cannabis-group-3",
"https://weedmaps.com/deliveries/beleave-10",
"https://weedmaps.com/doctors/alpha-cure-consulting-8",
"https://weedmaps.com/doctors/clinique-tetra-4",
"https://weedmaps.com/dispensaries/tweed-10",
"https://weedmaps.com/dispensaries/the-cannabis-co-yqr",
"https://weedmaps.com/dispensaries/fire-flower-yorkton-1",
"https://weedmaps.com/deliveries/budbargain-ca-2",
"https://weedmaps.com/dispensaries/wiid-boutique-inc",
"https://weedmaps.com/dispensaries/kelz-medical-services",
"https://weedmaps.com/deliveries/nikki-stikki-botanicals-2",
"https://weedmaps.com/dispensaries/lucid-cannabis-3",
"https://weedmaps.com/dispensaries/vatic-cannabis-co",
"https://weedmaps.com/dispensaries/5-buds-cannabis-1",
"https://weedmaps.com/deliveries/xpressgrass-8",
"https://weedmaps.com/deliveries/hot-grass-3",
"https://weedmaps.com/dispensaries/canaba-cannabis",
"https://weedmaps.com/dispensaries/prairie-cannabis-coming-soon",
"https://weedmaps.com/deliveries/nikki-stikki-botanicals-2",
"https://weedmaps.com/doctors/clinique-tetra-4",
"https://weedmaps.com/dispensaries/vatic-cannabis-co",
"https://weedmaps.com/dispensaries/lucid-cannabis-3",
"https://weedmaps.com/dispensaries/meta-cannabis-supply-co-12",
"https://weedmaps.com/deliveries/budbargain-ca-2",
"https://weedmaps.com/doctors/medical-cannabis-group-3",
"https://weedmaps.com/dispensaries/kelz-medical-services",
"https://weedmaps.com/dispensaries/spiritleaf-12",
"https://weedmaps.com/dispensaries/tweed-10",
"https://weedmaps.com/deliveries/bamboo-forest-3",
"https://weedmaps.com/doctors/cool-kind-8",
"https://weedmaps.com/dispensaries/new-leaf-emporium",
"https://weedmaps.com/dispensaries/the-cannabis-co-yqr",
"https://weedmaps.com/deliveries/beleave-10",
"https://weedmaps.com/deliveries/coast-to-coast-medicinals-regina",
"https://weedmaps.com/doctors/alpha-cure-consulting-8",
"https://weedmaps.com/deliveries/bud-365-3",
"https://weedmaps.com/dispensaries/wiid-boutique-inc",
"https://weedmaps.com/deliveries/xpressgrass-8",
"https://weedmaps.com/deliveries/hot-grass-3",
"https://weedmaps.com/dispensaries/prairie-records-2",
"https://weedmaps.com/deliveries/ganjaboyz-ca-1",
"https://weedmaps.com/dispensaries/5buds-cannabis",
"https://weedmaps.com/dispensaries/canaba-cannabis",
"https://weedmaps.com/deliveries/hot-grass-4",
"https://weedmaps.com/dispensaries/the-pot-shack",
"https://weedmaps.com/doctors/natural-health-services-7",
"https://weedmaps.com/dispensaries/prairie-records-3",
"https://weedmaps.com/dispensaries/kiaro",
"https://weedmaps.com/deliveries/west-coast-cannabis-2-1",
"https://weedmaps.com/deliveries/mota-cannabis-products-9",
"https://weedmaps.com/dispensaries/prairie-records",
"https://weedmaps.com/deliveries/thc-collection-4",
"https://weedmaps.com/doctors/go-greens-consulting",
"https://weedmaps.com/dispensaries/5-buds-cannabis-2",
"https://weedmaps.com/doctors/national-access-cannabis-saskatoon",
"https://weedmaps.com/doctors/curativecare-ca-3",
"https://weedmaps.com/dispensaries/living-skies-cannabis-coming-soon",
"https://weedmaps.com/dispensaries/prairie-cannabis-coming-soon",
"https://weedmaps.com/deliveries/coast-to-coast-medicinals-15",
"https://weedmaps.com/dispensaries/lush-leaf-cannabis-ltd-comingsoon",
"https://weedmaps.com/dispensaries/clarity-cannabis-sk",
"https://weedmaps.com/dispensaries/5-buds-cannabis-1",
"https://weedmaps.com/dispensaries/fire-flower-yorkton-1",
"https://weedmaps.com/dispensaries/triple-j-s-canna-space-3",
"https://weedmaps.com/doctors/curativecare-ca-11",
"https://weedmaps.com/doctors/clinique-tetra-6",
"https://weedmaps.com/doctors/o-cannabis-clinic-9",
"https://weedmaps.com/doctors/medical-cannabis-group-12",
"https://weedmaps.com/deliveries/hot-grass-14"
    ]

    const browser = await puppeteer.launch({
        headless: false
    })



    let promises = [];


    for (url of list) {
        const page = await browser.newPage()

        try {
            await page.goto(url)
        } catch (e) {
            console.log("process..." + url + "...fail")
            console.log(e)
        }

        const _age_pop = await page.$x('//button[@class="sc-gzVnrw cXxGTL"]')

        _age_pop.length > 1 ? await _age_pop[0].click() : ""

        promises.push(
            /**
             * this data already conten prods list
             * could get the list prods from this data
             * */
            await page.$$eval('#__NEXT_DATA__', (scripts, url) => {

                let _return = ""
                const status_code = JSON.parse(scripts[0].lastChild.data)["props"]["statusCode"]
                let _listing = JSON.parse(scripts[0].lastChild.data)["props"]["storeInitialState"]["listing"]["listing"]
                let _location = JSON.parse(scripts[0].lastChild.data)["props"]["storeInitialState"]["location"]["current"]

                if (status_code == 200) {
                    _return = {
                        _url: url,
                        status: status_code,
                        name: _listing["name"],
                        email: _listing["email"],
                        web: _listing["website"],
                        logo: _listing["avatar_image"]["original_url"],
                        description: _listing["description"],
                        phone: _listing["phone_number"].toString(),
                        address: _listing["address"],
                        city: _listing["city"],
                        region: _listing["state"],
                        longlat: _listing["longitude"] + " : " + _listing["latitude"],
                        zipcode: _listing["zipcode"],


                    }

                } else {
                    _return = {
                        _url: url,
                        status: status_code,
                    }

                }


                return _return;
            }, url)
        )
        await page.close()

        //TODO: tracing
        console.log("process...done: " + url.substr(20, 50))
    }

    await browser.close()

    for (retailer of promises) {
        // console.log(retailer)
        try {
            var csv = JSONToCSV(retailer, {
                fields: ["status", "_url", "name", "email", "web", "logo", "phone", "address", "city", "region", "longlat", "description"],
                header: false
            });

            // console.log(csv)
        } catch (err) {
            console.log(err)
        }

        /**
         * TODO: ISSUE
         * const path = './result/csv_exp_retailers' + new Date().getTime() / 1000 + '.csv'
         * --> split to 2 files bcs the process time long and the file name dynamic
         */

        const _file = '.././result/csv_exp_retailers.csv'
        /**
         * add new line: "\r\n"
         * append in file: {flag:"a+"}
         */
        writeFile.writeFile(_file, csv + "\r\n", {
            flag: "a+"
        }, (err) => {
            if (err) {
                console.log(err); // Do something to handle the error or just throw it
                throw new Error(err);
            }
        })

    }
    console.log('...Export csv Success!');

})()